// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppInput: typeof import('./../src/components/AppInput.vue')['default']
    AsyncContacts: typeof import('./../src/views/contacts/components/AsyncContacts.vue')['default']
    AsyncExample: typeof import('./../src/views/contacts/components/AsyncExample.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    ContactItem: typeof import('./../src/views/contacts/components/ContactItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    IconEnvelope: typeof import('./../src/components/icons/IconEnvelope.vue')['default']
    IconPhone: typeof import('./../src/components/icons/IconPhone.vue')['default']
    IconPlus: typeof import('./../src/components/icons/IconPlus.vue')['default']
    LazyImage: typeof import('./../src/components/LazyImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
