// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppDropdown: typeof import('./../src/components/app-dropdown/AppDropdown.vue')['default']
    AppDropdownList: typeof import('./../src/components/app-dropdown/AppDropdownList.vue')['default']
    AppDropdownSelectedItems: typeof import('./../src/components/app-dropdown/AppDropdownSelectedItems.vue')['default']
    AppInput: typeof import('./../src/components/AppInput.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    ContactItem: typeof import('./../src/views/contacts/components/ContactItem.vue')['default']
    DepartmentItem: typeof import('./../src/views/job-openings/components/DepartmentItem.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    IconArrow: typeof import('./../src/components/icons/IconArrow.vue')['default']
    IconCloseCross: typeof import('./../src/components/icons/IconCloseCross.vue')['default']
    IconEnvelope: typeof import('./../src/components/icons/IconEnvelope.vue')['default']
    IconPhone: typeof import('./../src/components/icons/IconPhone.vue')['default']
    IconPlus: typeof import('./../src/components/icons/IconPlus.vue')['default']
    JobOpeningsFilter: typeof import('./../src/views/job-openings/components/JobOpeningsFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
